# permissions for end users to edit redisnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisnode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisnode-editor-role
rules:
- apiGroups:
  - redis-node.k8s-operator.com
  resources:
  - redisnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis-node.k8s-operator.com
  resources:
  - redisnodes/status
  verbs:
  - get
